# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-17 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_ip',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
