# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180118_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
