# Generated by Django 2.0.1 on 2018-01-21 20:06

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_user_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='item_delivery',
            field=models.DateTimeField(default=website.models.User.time_under_timezone, verbose_name='Date of Delivery'),
        ),
    ]
