# Generated by Django 2.0.1 on 2018-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_grocery'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='url',
            field=models.ImageField(default='', null=True, upload_to='groceries'),
        ),
    ]
