# Generated by Django 2.0.1 on 2018-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_grocery_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='', max_length=200, null=True)),
                ('email_host_password', models.CharField(default='', max_length=200, null=True)),
                ('email_host_user', models.CharField(default='', max_length=200, null=True)),
                ('server_notifier', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
