# Generated by Django 2.0.1 on 2018-05-05 14:40

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_totals', models.CharField(max_length=200, null=True)),
                ('item_quantities', models.CharField(max_length=200, null=True)),
                ('item_indexes', models.CharField(max_length=200, null=True)),
                ('item_descriptions', models.CharField(max_length=200, null=True)),
                ('item_delivery', models.DateTimeField(default=website.models.Customer.time_under_timezone, verbose_name='Date of Delivery')),
                ('purchase_date', models.DateTimeField(default=website.models.Customer.time_under_timezone, verbose_name='Date of Purchase')),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
