# Generated by Django 2.0.1 on 2018-05-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180505_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='fail_proof_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
