# Generated by Django 2.0.1 on 2018-05-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_grocery_fail_proof_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='fail_proof_url',
        ),
    ]
